### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by gumme** [micahlmartin/XmlTransformer#2]
There is no license attached to your project, which strictly speaking stops everyone from using your program in a legal way (with or without changes).
Unless this is your intention, I suggest that you add a license file. If licensing is a new area for you there are plenty of resources on why to license and which license you should choose.

Your project seems to work very good, and actually the best of all alternatives I have tried when it comes to keep source-file formatting. So would be really nice if you could add an explicit license to your project :)

**Comment by micahlmartin** [comment]
Done! https://github.com/micahlmartin/XmlTransformer/blob/master/LICENSE.md
